"""HTML reporter — renders a self-contained HTML report."""

from __future__ import annotations

from jinja2 import Environment, select_autoescape

from dq_framework.models import SuiteResult
from dq_framework.reporters.base import Reporter


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>DQ Report — {{ result.suite_name }}</title>
<style>
  :root {
    --bg: #f8fafc;
    --card: #ffffff;
    --border: #e2e8f0;
    --text: #0f172a;
    --muted: #64748b;
    --green: #16a34a;
    --red: #dc2626;
    --orange: #ea580c;
    --blue: #2563eb;
    --yellow: #ca8a04;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    background: var(--bg);
    color: var(--text);
    margin: 0;
    padding: 2rem;
    line-height: 1.5;
  }
  .container { max-width: 1080px; margin: 0 auto; }
  header { margin-bottom: 2rem; }
  h1 { margin: 0 0 0.25rem; font-size: 1.75rem; }
  .subtitle { color: var(--muted); font-size: 0.95rem; }
  .stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 1rem;
    margin: 1.5rem 0;
  }
  .stat {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem 1.25rem;
  }
  .stat-label {
    color: var(--muted);
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }
  .stat-value { font-size: 1.5rem; font-weight: 600; margin-top: 0.25rem; }
  .status-passed { color: var(--green); }
  .status-failed { color: var(--red); }
  .status-error { color: var(--orange); }
  table {
    width: 100%;
    border-collapse: collapse;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    overflow: hidden;
  }
  th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { background: #f1f5f9; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--muted); }
  tr:last-child td { border-bottom: none; }
  .badge {
    display: inline-block;
    padding: 0.15rem 0.55rem;
    border-radius: 999px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
  }
  .badge-passed { background: #dcfce7; color: var(--green); }
  .badge-failed { background: #fee2e2; color: var(--red); }
  .badge-error  { background: #ffedd5; color: var(--orange); }
  .badge-skipped { background: #e2e8f0; color: var(--muted); }
  .sev-info { color: var(--blue); }
  .sev-warning { color: var(--yellow); }
  .sev-critical { color: var(--red); font-weight: 600; }
  footer { margin-top: 2rem; color: var(--muted); font-size: 0.85rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>{{ result.suite_name }}</h1>
    <div class="subtitle">Table: <code>{{ result.table }}</code></div>
  </header>

  <div class="stats">
    <div class="stat">
      <div class="stat-label">Status</div>
      <div class="stat-value status-{{ result.status.value }}">{{ result.status.value|upper }}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Pass rate</div>
      <div class="stat-value">{{ "%.1f"|format(result.pass_rate * 100) }}%</div>
    </div>
    <div class="stat">
      <div class="stat-label">Checks</div>
      <div class="stat-value">{{ result.results|length }}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Duration</div>
      <div class="stat-value">{{ "%.1f"|format(result.duration_ms) }} ms</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Check</th>
        <th>Column</th>
        <th>Severity</th>
        <th>Status</th>
        <th>Message</th>
        <th style="text-align:right">Time (ms)</th>
      </tr>
    </thead>
    <tbody>
      {% for r in result.results %}
      <tr>
        <td><code>{{ r.check_name }}</code></td>
        <td>{{ r.metadata.get("column") or "—" }}</td>
        <td class="sev-{{ r.severity.value }}">{{ r.severity.value }}</td>
        <td><span class="badge badge-{{ r.status.value }}">{{ r.status.value }}</span></td>
        <td>{{ r.message }}</td>
        <td style="text-align:right">{{ "%.1f"|format(r.duration_ms) }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <footer>
    Generated by <strong>dq-framework</strong> at {{ result.finished_at.strftime("%Y-%m-%d %H:%M:%S UTC") }}
  </footer>
</div>
</body>
</html>
"""


class HTMLReporter(Reporter):
    """Render a SuiteResult as a self-contained HTML page."""

    format_name = "html"

    def __init__(self) -> None:
        self._env = Environment(autoescape=select_autoescape(["html"]))
        self._template = self._env.from_string(HTML_TEMPLATE)

    def render(self, result: SuiteResult) -> str:
        return self._template.render(result=result)